### ISSUE TITLE
Error when using GET / 

### ISSUE THREAD

**Issue by luketoh** [ericmagnuson/rmcontrol#11]
Hi Eric,

After sudo python run.py , I get the following when I load the webpage, and enter GET / , and then click on the + sign.  Any ideas what is wrong?

pi@hassbian:/home/rmcontrol $ sudo python run.py
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
192.168.0.100 - - [18/Feb/2017 17:18:50] "GET / HTTP/1.1" 200 -
192.168.0.100 - - [18/Feb/2017 17:18:50] "GET /static/app.css HTTP/1.1" 304 -
192.168.0.100 - - [18/Feb/2017 17:18:50] "GET /static/app.js HTTP/1.1" 304 -
192.168.0.100 - - [18/Feb/2017 17:18:50] "GET /commands HTTP/1.1" 200 -
^C----------------------------------------
Exception happened during processing of request from ('192.168.0.100', 59171)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/dist-packages/Werkzeug-0.11.15-py2.7.egg/werkzeug/serving.py", line 228, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/local/lib/python2.7/dist-packages/Werkzeug-0.11.15-py2.7.egg/werkzeug/serving.py", line 263, in handle_one_request
    return self.run_wsgi()
  File "/usr/local/lib/python2.7/dist-packages/Werkzeug-0.11.15-py2.7.egg/werkzeug/serving.py", line 205, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/Werkzeug-0.11.15-py2.7.egg/werkzeug/serving.py", line 193, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.12-py2.7.egg/flask/app.py", line 1994, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.12-py2.7.egg/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.12-py2.7.egg/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.12-py2.7.egg/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/rmcontrol/rmcontrol/__init__.py", line 142, in create
    device = get_device()
  File "/home/rmcontrol/rmcontrol/__init__.py", line 85, in get_device
    device.discover()
  File "/usr/local/lib/python2.7/dist-packages/broadlink-0.3-py2.7.egg/broadlink/__init__.py", line 477, in discover
    dev = discover()
  File "/usr/local/lib/python2.7/dist-packages/broadlink-0.3-py2.7.egg/broadlink/__init__.py", line 110, in discover
    response = cs.recvfrom(1024)
KeyboardInterrupt
----------------------------------------

**Comment by luketoh** [comment]
Please ignore the above.  I found out that my RM3 Pro was on a guest wireless network and wasn't accessible by the Raspberry Pi that this script was running on.  Funnily my desktop could ping the RM3 Pro though, eventhough both the desktop and Raspberry Pi are both on the same non-guest network.

**Comment by ericmagnuson** [comment]
Glad you figured it out.  Right now, RM Control doesn't handle networking errors gracefully.  That's definitely something to be added soon!
