### ISSUE TITLE
Thanks..

### ISSUE THREAD

**Issue by pandan129** [ericmagnuson/rmcontrol#7]
acdeMac-mini:~ mac$ export FLASK_APP=rmcontrol; python -m flask initdb
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Flask-0.12-py2.7.egg/flask/__init__.py", line 17, in <module>
    from werkzeug.exceptions import abort
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Werkzeug-0.11.15-py2.7.egg/werkzeug/__init__.py", line 152, in <module>
    __import__('werkzeug.exceptions')
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Werkzeug-0.11.15-py2.7.egg/werkzeug/exceptions.py", line 71, in <module>
    from werkzeug.wrappers import Response
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Werkzeug-0.11.15-py2.7.egg/werkzeug/wrappers.py", line 26, in <module>
    from werkzeug.http import HTTP_STATUS_CODES, \
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Werkzeug-0.11.15-py2.7.egg/werkzeug/http.py", line 28, in <module>
    from urllib.request import parse_http_list as _parse_list_header
ImportError: No module named request

**Comment by luketoh** [comment]
I think you need to run the command whilst in the rmcontrol folder

**Comment by ericmagnuson** [comment]
What version of python are you using?

**Comment by luketoh** [comment]
@pandan129 Also check that your folders and file permissions are correctly set for the rmcontrol folders and subfolders and files within.
